service: serverless-boilerplate
frameworkVersion: "3"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: false
      seed: false
    stages:
      - local
      - dev
    seed:
      dev:
        sources:
          - table: documents
            sources: [./src/database/seeds/documents.json]
    migrations:
      dev:
        sources:
          - table: documents
            sources: [./src/database/migrations/documents.json]

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Scan
            - dynamodb:Query
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [DocumentsTable, Arn]

functions:
  readDocuments:
    timeout: 30
    handler: src/functions/documents/read.handler
    events:
      - http:
          path: /documents
          method: get
  createDocuments:
    timeout: 30
    handler: src/functions/documents/create.handler
    events:
      - http:
          path: /documents
          method: post
  updateDocuments:
    timeout: 30
    handler: src/functions/documents/update.handler
    events:
      - http:
          path: /documents/{id}
          method: put
  deleteDocuments:
    timeout: 30
    handler: src/functions/documents/delete.handler
    events:
      - http:
          path: /documents/{id}
          method: delete

resources:
  Resources:
    DocumentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: documents
